{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dev-workspaces.fullname" . }}
  labels:
    {{- include "dev-workspaces.labels" . | nindent 4 }}
    {{- with .Values.configMap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annotations := merge (dict) .Values.configMap.annotations (include "dev-workspaces.annotations" . | fromYaml) }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $name, $content := .Values.configMap.files }}
  {{ $name }}: |-
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
